In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [40]:
!curl -L "https://drive.google.com/uc?export=download&id=1RN3Fncv6sypLDHRjYDlQlKC_ATXC5yB6" -o car_data.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 18131  100 18131    0     0  11755      0  0:00:01  0:00:01 --:--:--  983k

In [41]:
df = pd.read_csv("car_data.csv")
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [42]:
df.sample()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
364,26.6,8,350.0,105,3725,19.0,81,1,oldsmobile cutlass ls

In [43]:
df = df.drop('car name', axis=1)

In [44]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,18.0,8,307.0,130,3504,12.0,70,1
1,15.0,8,350.0,165,3693,11.5,70,1
2,18.0,8,318.0,150,3436,11.0,70,1
3,16.0,8,304.0,150,3433,12.0,70,1
4,17.0,8,302.0,140,3449,10.5,70,1

In [45]:
df.origin = df.origin.replace({1: 'america', 2: 'Europe', 3: 'asia'})
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,18.0,8,307.0,130,3504,12.0,70,america
1,15.0,8,350.0,165,3693,11.5,70,america
2,18.0,8,318.0,150,3436,11.0,70,america
3,16.0,8,304.0,150,3433,12.0,70,america
4,17.0,8,302.0,140,3449,10.5,70,america

In [46]:
df = pd.get_dummies(df, columns=['origin'], drop_first=True )
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin_america,origin_asia
0,18.0,8,307.0,130,3504,12.0,70,True,False
1,15.0,8,350.0,165,3693,11.5,70,True,False
2,18.0,8,318.0,150,3436,11.0,70,True,False
3,16.0,8,304.0,150,3433,12.0,70,True,False
4,17.0,8,302.0,140,3449,10.5,70,True,False

In [47]:
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000

In [48]:
df.dtypes

mpg               float64
cylinders           int64
displacement      float64
horsepower         object
weight              int64
acceleration      float64
model year          int64
origin_america       bool
origin_asia          bool
dtype: object

In [49]:
df.isnull().sum()

mpg               0
cylinders         0
displacement      0
horsepower        0
weight            0
acceleration      0
model year        0
origin_america    0
origin_asia       0
dtype: int64

In [50]:
df.horsepower.str.isdigit()

0      True
1      True
2      True
3      True
4      True
       ...
393    True
394    True
395    True
396    True
397    True
Name: horsepower, Length: 398, dtype: bool

In [54]:
hpisdigit = pd.DataFrame(df.horsepower.str.isdigit())

df[hpisdigit.horsepower == False]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin_america,origin_asia
32,25.0,4,98.0,?,2046,19.0,71,True,False
126,21.0,6,200.0,?,2875,17.0,74,True,False
330,40.9,4,85.0,?,1835,17.3,80,False,False
336,23.6,4,140.0,?,2905,14.3,80,True,False
354,34.5,4,100.0,?,2320,15.8,81,False,False
374,23.0,4,151.0,?,3035,20.5,82,True,False

In [56]:
df = df.replace('?', np.nan)

In [57]:
df.isnull().sum()

mpg               0
cylinders         0
displacement      0
horsepower        6
weight            0
acceleration      0
model year        0
origin_america    0
origin_asia       0
dtype: int64

In [58]:
df = df.apply(lambda x: x.fillna(x.median()), axis=1)

In [59]:
X = df.drop('mpg', axis=1)
y = df.mpg
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [60]:
len(X_train)/len(X)

0.6984924623115578

In [63]:
len(X_test)/len(X)

0.3015075376884422

In [64]:
regression_model = LinearRegression()
regression_model

LinearRegression()

In [66]:
regression_model.fit(X_train, y_train)

LinearRegression()

In [69]:
X

,cylinders,displacement,horsepower,weight,acceleration,model year,origin_america,origin_asia
0,8,307.0,130,3504,12.0,70,True,False
1,8,350.0,165,3693,11.5,70,True,False
2,8,318.0,150,3436,11.0,70,True,False
3,8,304.0,150,3433,12.0,70,True,False
4,8,302.0,140,3449,10.5,70,True,False
...,...,...,...,...,...,...,...,...
393,4,140.0,86,2790,15.6,82,True,False
394,4,97.0,52,2130,24.6,82,False,False
395,4,135.0,84,2295,11.6,82,True,False
396,4,120.0,79,2625,18.6,82,True,False
397,4,119.0,82,2720,19.4,82,True,False

In [67]:
regression_model.coef_

array([-0.39245606,  0.02843961, -0.01408293, -0.00754043,  0.09319116,
        0.84130098, -2.99210458, -0.60679379])

In [ ]:
for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, regression_model.coef_[idx]))

The coefficient for cylinders is -0.39245605950077306
The coefficient for displacement is 0.028439607048743733
The coefficient for horsepower is -0.014082934526127659
The coefficient for weight is -0.007540425279049746
The coefficient for acceleration is 0.09319115585677416
The coefficient for model year is 0.841300983513779
The coefficient for origin_america is -2.992104580745181
The coefficient for origin_asia is -0.6067937867021923

In [73]:
regression_model.score(X_test, y_test)

0.8449486999431458

In [74]:
regression_model.score(X_train, y_train)

/Users/nithinys/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Users/nithinys/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Users/nithinys/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_base.py:279: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_

0.8135475642970712