In [1]:
import pandas as pd
import numpy as np

In [2]:
!gdown 16KtxSt_QEGQvfluEaMls5cCHPwhRXgCk
!gdown 19L3rYatfhbBL1r5MHrv-p_oM2wlvrhqk
!gdown 1OHLKJwA3qZopKPvlKoRldM6BvA1A4dYF
!gdown 1N7O_fWCTJLu8SIa_paKcDEzllgpMk8sK
!gdown 12Bh2AN8LcZAlg20ehpQrEWccUDaSdsOG

/Users/nithinys/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=16KtxSt_QEGQvfluEaMls5cCHPwhRXgCk
To: /Users/nithinys/GithubRepos/ml-ai-genai-ds-journal/module04-ML-coding:Suprivised-learing/ensemble_model/HR-Employee-Attrition.csv
100%|████████████████████████████████████████| 228k/228k [00:00<00:00, 1.02MB/s]
/Users/nithinys/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=19L3rYatfhbBL1r5MHrv-p_oM2wlvrhqk
To: /Users/nithinys/GithubRepos/ml-ai-genai-ds-journal/module04-ML-coding:Suprivised-learing/ensemble_model/preprocessed_X_sm.pickle
100%|█████████████████████████████████████████| 534k/534k [00:01<00:00, 282kB/s]
/Users/nithinys/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1OHLKJwA3qZopKPvlKoRldM6BvA1A4dYF
To: /Users/nithinys/GithubRepos/ml-ai-genai-ds-journal/module04-ML-coding:Suprivised-learing/ensemble_model/X_test.pickle
100%|█████████████████████████████████████████| 111k/111k [00:00<00:00, 496kB/s]
/Users/nithinys/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1N7O_fWCTJLu8SIa_paKcDEzllgpMk8sK
To: /Users/nithinys/GithubRepos/ml-ai-genai-ds-journal/module04-ML-coding:Suprivised-learing/ensemble_model/y_sm.pickle
100%|██████████████████████████████████████| 15.4k/15.4k [00:00<00:00, 24.8MB/s]
/Users/nithinys/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=12Bh2AN8LcZAlg20ehpQrEWccUDaSdsOG
To: /Users/nithinys/GithubRepos/ml-ai-genai-ds-journal/module04-ML-coding:Suprivised-learing/ensemble_model/y_test.pickle
100%|██████████████████████████████████████| 9.49k/9.49k [00:00<00:00, 24.2MB/s]

In [3]:
pd.read_pickle("preprocessed_X_sm.pickle")

,Age,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,YearsWithCurrManager,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,36,1174,3,4,0.233871,1,0,99,3,2,...,1,0.000000,0.000000,1.0,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
1,21,546,5,1,0.127479,3,1,97,3,1,...,2,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
2,43,422,1,3,0.151584,4,0,33,3,2,...,2,0.000000,1.000000,0.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
3,42,188,29,3,0.127479,2,1,56,1,2,...,0,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
4,35,992,1,3,0.127479,4,1,68,2,1,...,2,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1843,41,1077,10,3,0.187471,2,1,85,2,2,...,4,0.407817,0.592183,0.0,0.000000,0.407817,0.592183,0.592183,0.000000,0.407817
1844,55,310,7,1,0.239573,3,1,71,3,1,...,7,0.000000,0.000000,1.0,0.000000,0.998141,0.001859,0.000000,0.998141,0.001859
1845,36,899,5,2,0.143813,1,0,92,2,1,...,2,0.677643,0.322357,0.0,0.000000,1.000000,0.000000,0.677643,0.322357,0.000000
1846,40,292,7,3,0.151584,1,1,84,3,3,...,5,0.192577,0.807423,0.0,0.000000,1.000000,0.000000,0.807423,0.192577,0.000000
1847,19,936,8,2,0.157015,3,0,85,2,1,...,0,0.000000,0.000000,1.0,0.263474,0.736526,0.000000,0.000000,0.000000,1.000000

In [4]:
# import pickle
# Load data (deserialize)
with open('preprocessed_X_sm.pickle', 'rb') as handle:
    # X_train = pickle.load(handle)
    X_train = pd.read_pickle("preprocessed_X_sm.pickle")

with open('X_test.pickle', 'rb') as handle:
    # X_test = pickle.load(handle)
    X_test = pd.read_pickle("X_test.pickle")


with open('y_sm.pickle', 'rb') as handle:
    # y_train = pickle.load(handle)
    y_train = pd.read_pickle("y_sm.pickle")


with open('y_test.pickle', 'rb') as handle:
    # y_test = pickle.load(handle)
    y_test = pd.read_pickle("y_test.pickle")

In [5]:
y_train

0       0
1       0
2       0
3       0
4       0
       ..
1843    1
1844    1
1845    1
1846    1
1847    1
Name: Attrition, Length: 1848, dtype: int64

In [6]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(random_state=7, max_depth=4)
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=7)

In [7]:
print("Train accuracy: {:.2f}".format(tree_clf.score(X_train, y_train)*100))
print("Test accuracy: {:.2f}".format(tree_clf.score(X_test, y_test)*100))

Train accuracy: 83.77
Test accuracy: 78.80

In [8]:
X_train.shape

(1848, 36)

In [9]:
df = X_train.copy()
df['target'] = y_train.values

In [10]:
df.head()

,Age,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,target
0,36,1174,3,4,0.233871,1,0,99,3,2,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
1,21,546,5,1,0.127479,3,1,97,3,1,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0
2,43,422,1,3,0.151584,4,0,33,3,2,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0
3,42,188,29,3,0.127479,2,1,56,1,2,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0
4,35,992,1,3,0.127479,4,1,68,2,1,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0

In [11]:
df.shape[0]

1848

In [12]:
# function for row sampling

def sample_rows(df,percent):
  return df.sample(int(percent*df.shape[0]),replace=True)

In [13]:
sample_rows(df.head(),0.9)

,Age,DailyRate,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,...,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,target
3,42,188,29,3,0.127479,2,1,56,1,2,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0
4,35,992,1,3,0.127479,4,1,68,2,1,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0
2,43,422,1,3,0.151584,4,0,33,3,2,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0
0,36,1174,3,4,0.233871,1,0,99,3,2,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0

In [14]:
1848*0.2

369.6

In [15]:
df.columns.tolist()[:-1]

['Age',
 'DailyRate',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager',
 'BusinessTravel_Non-Travel',
 'BusinessTravel_Travel_Frequently',
 'BusinessTravel_Travel_Rarely',
 'Department_Human Resources',
 'Department_Research & Development',
 'Department_Sales',
 'MaritalStatus_Divorced',
 'MaritalStatus_Married',
 'MaritalStatus_Single']

In [16]:
df.shape[1]

37

In [17]:
import random
random.sample(df.columns.tolist()[:-1],int(0.5*(df.shape[1]-1)))

['WorkLifeBalance',
 'YearsWithCurrManager',
 'BusinessTravel_Non-Travel',
 'BusinessTravel_Travel_Rarely',
 'TotalWorkingYears',
 'Department_Sales',
 'YearsAtCompany',
 'JobInvolvement',
 'MaritalStatus_Divorced',
 'BusinessTravel_Travel_Frequently',
 'Department_Human Resources',
 'TrainingTimesLastYear',
 'Department_Research & Development',
 'JobRole',
 'StockOptionLevel',
 'HourlyRate',
 'Education',
 'PercentSalaryHike']

In [18]:
# function for feature sampling

def sample_features(df,percent):
  cols = random.sample(df.columns.tolist()[:-1],int(percent*(df.shape[1]-1)))
  new_df = df[cols]
  new_df['target'] = df['target']
  return new_df

In [19]:
36*0.2

7.2

In [20]:
sample_features(df,0.2)

/var/folders/96/pzp77pgj2jngfzbn1nyzz6w80000gn/T/ipykernel_44776/1367481554.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']

,OverTime,Education,Department_Human Resources,Gender,Age,MonthlyIncome,JobInvolvement,target
0,1,4,0.000000,0,36,9278,3,0
1,0,1,0.000000,1,21,3117,3,0
2,0,3,0.000000,0,43,5562,3,0
3,0,3,0.000000,1,42,4272,1,0
4,0,3,0.000000,1,35,2450,2,0
...,...,...,...,...,...,...,...,...
1843,0,3,0.000000,1,41,7541,2,1
1844,0,1,0.000000,1,55,2339,3,1
1845,0,2,0.000000,0,36,2190,2,1
1846,0,3,0.000000,1,40,12107,3,1
1847,0,2,0.263474,0,19,2590,2,1

In [21]:
def combined_sampling(df,row_percent,col_percent):
  new_df = sample_rows(df,row_percent)
  return sample_features(new_df,col_percent)

In [22]:
combined_sampling(df,0.5,0.5)

/var/folders/96/pzp77pgj2jngfzbn1nyzz6w80000gn/T/ipykernel_44776/1367481554.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']

,BusinessTravel_Non-Travel,StockOptionLevel,NumCompaniesWorked,MaritalStatus_Single,DistanceFromHome,JobLevel,Education,YearsInCurrentRole,TrainingTimesLastYear,YearsWithCurrManager,MaritalStatus_Divorced,Age,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,RelationshipSatisfaction,Department_Sales,DailyRate,YearsAtCompany,target
1411,0.0,0,1,1.0,2,1,2,0,2,0,0.0,19,0.0,1.0,2,0.000000,540,1,1
104,0.0,0,7,1.0,10,3,1,3,3,2,0.0,39,0.0,1.0,3,0.000000,1253,4,0
1577,0.0,1,3,0.0,21,2,1,7,2,7,0.0,40,0.0,1.0,3,0.301848,305,9,1
388,0.0,1,1,0.0,4,1,1,7,3,6,0.0,25,0.0,1.0,2,0.000000,1219,7,1
28,0.0,3,3,0.0,19,2,3,3,2,2,0.0,37,0.0,1.0,1,0.000000,671,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,0.0,1,4,0.0,2,1,3,2,3,2,0.0,36,0.0,1.0,2,0.000000,329,2,0
290,0.0,1,1,0.0,10,1,3,2,4,2,1.0,35,0.0,1.0,1,0.000000,802,3,0
91,0.0,0,7,0.0,7,3,4,9,0,9,0.0,58,0.0,1.0,4,0.000000,601,10,1
924,0.0,1,4,0.0,8,3,2,9,3,7,0.0,49,0.0,1.0,3,0.000000,527,26,0
479,0.0,2,0,0.0,1,2,4,13,3,8,0.0,38,0.0,1.0,1,1.000000,1321,15,0

In [23]:
df1 = combined_sampling(df,0.5,0.5)
df1

/var/folders/96/pzp77pgj2jngfzbn1nyzz6w80000gn/T/ipykernel_44776/1367481554.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']

,BusinessTravel_Non-Travel,OverTime,BusinessTravel_Travel_Rarely,Department_Sales,JobRole,NumCompaniesWorked,JobLevel,JobSatisfaction,Gender,HourlyRate,RelationshipSatisfaction,JobInvolvement,PercentSalaryHike,MaritalStatus_Divorced,YearsInCurrentRole,Age,YearsWithCurrManager,MonthlyIncome,target
480,0.0,0,0.0,1.0,0.174089,1,2,3,0,90,4,3,14,0.000000,7,27,7,9981,0
1214,0.0,0,1.0,0.0,0.182210,3,1,2,0,55,1,3,20,0.260012,0,52,0,2373,1
901,0.0,0,1.0,0.0,0.160714,1,1,2,0,43,4,3,13,0.000000,1,22,2,2244,0
1392,0.0,0,1.0,0.0,0.234100,1,1,3,1,51,3,3,12,0.000000,0,18,0,1373,1
828,0.0,0,1.0,0.0,0.030303,5,3,1,0,50,3,2,15,1.000000,11,50,11,13269,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,0.0,1,0.0,0.0,0.243386,3,1,3,1,43,4,3,22,1.000000,0,44,0,3161,1
1420,0.0,1,1.0,1.0,0.174089,4,2,3,0,78,1,1,16,0.000000,6,32,6,6146,1
964,0.0,0,1.0,0.0,0.160714,1,1,2,1,48,2,2,12,0.000000,4,30,1,2141,0
197,0.0,0,1.0,1.0,0.030769,3,5,4,0,68,3,3,11,1.000000,0,50,6,19517,0
1010,0.0,1,1.0,0.0,0.243386,2,1,4,1,62,3,4,24,0.000000,2,44,2,2818,0

In [47]:
df2 = combined_sampling(df,0.5,0.5)
df2

/var/folders/96/pzp77pgj2jngfzbn1nyzz6w80000gn/T/ipykernel_44776/1367481554.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']

,MonthlyRate,YearsSinceLastPromotion,YearsInCurrentRole,JobSatisfaction,TrainingTimesLastYear,Department_Sales,DistanceFromHome,DailyRate,BusinessTravel_Travel_Frequently,Age,RelationshipSatisfaction,Department_Human Resources,EnvironmentSatisfaction,JobInvolvement,YearsWithCurrManager,JobLevel,YearsAtCompany,WorkLifeBalance,target
1785,13804,0,7,1,2,0.875112,11,1267,0.000000,43,2,0.0,2,2,7,3,8,2,1
1520,17015,0,0,1,5,0.195375,9,1257,0.000000,22,1,0.0,2,2,0,1,1,2,1
942,17434,0,0,2,3,1.000000,2,202,0.000000,30,1,0.0,3,3,0,1,1,3,0
1778,9058,3,7,1,2,0.109746,2,1309,0.890254,31,1,0.0,2,3,6,3,8,2,1
915,13596,4,8,4,3,1.000000,9,669,0.000000,46,4,0.0,3,2,7,3,9,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1029,19373,0,1,3,0,0.000000,21,1330,0.000000,26,3,0.0,1,3,0,1,1,2,1
201,22887,0,7,3,3,0.000000,7,658,1.000000,34,4,0.0,1,1,6,2,9,3,1
216,8416,5,3,3,3,0.000000,2,1303,0.000000,34,3,0.0,4,2,7,1,7,3,0
84,24439,0,2,2,1,0.000000,11,1405,0.000000,51,2,0.0,4,2,3,4,5,2,0
1796,18604,0,2,1,2,1.000000,7,703,0.000000,34,1,0.0,1,3,3,2,5,2,1

In [25]:
df3 = combined_sampling(df,0.5,0.5)
df3

/var/folders/96/pzp77pgj2jngfzbn1nyzz6w80000gn/T/ipykernel_44776/1367481554.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['target'] = df['target']

,WorkLifeBalance,Department_Sales,Gender,TotalWorkingYears,YearsInCurrentRole,Age,Department_Human Resources,RelationshipSatisfaction,TrainingTimesLastYear,NumCompaniesWorked,StockOptionLevel,BusinessTravel_Travel_Rarely,Department_Research & Development,JobLevel,YearsAtCompany,EnvironmentSatisfaction,OverTime,Education,target
1000,3,0.000000,1,5,3,26,0.0,3,3,1,1,0.000000,1.000000,2,5,1,1,2,0
1483,3,0.000000,1,3,1,27,0.0,1,2,0,1,0.000000,1.000000,1,3,1,0,2,1
1220,2,0.289311,0,1,0,23,0.0,1,5,1,0,0.710689,0.710689,1,1,2,0,3,1
761,3,0.000000,0,9,2,34,0.0,4,3,2,0,1.000000,1.000000,1,3,4,0,2,0
654,4,0.000000,1,31,7,55,0.0,4,4,2,2,1.000000,1.000000,4,7,2,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,2,0.000000,1,8,2,45,0.0,4,3,3,2,1.000000,1.000000,1,2,1,0,2,0
987,3,1.000000,0,28,15,46,0.0,1,2,8,0,1.000000,0.000000,4,26,3,0,3,0
954,3,0.000000,0,6,3,24,0.0,3,2,1,0,0.000000,1.000000,1,6,1,1,1,0
1482,2,0.662922,1,10,2,30,0.0,1,2,4,0,0.662922,0.337078,2,3,1,0,2,1
484,3,1.000000,0,10,7,36,0.0,3,6,0,1,0.000000,0.000000,3,9,2,0,2,0

In [26]:
print(df1.columns)
print(df2.columns)
print(df3.columns)

Index(['BusinessTravel_Non-Travel', 'OverTime', 'BusinessTravel_Travel_Rarely',
       'Department_Sales', 'JobRole', 'NumCompaniesWorked', 'JobLevel',
       'JobSatisfaction', 'Gender', 'HourlyRate', 'RelationshipSatisfaction',
       'JobInvolvement', 'PercentSalaryHike', 'MaritalStatus_Divorced',
       'YearsInCurrentRole', 'Age', 'YearsWithCurrManager', 'MonthlyIncome',
       'target'],
      dtype='object')
Index(['Gender', 'WorkLifeBalance', 'JobInvolvement', 'JobSatisfaction',
       'YearsAtCompany', 'OverTime', 'EducationField', 'PercentSalaryHike',
       'NumCompaniesWorked', 'MonthlyIncome', 'DailyRate',
       'YearsSinceLastPromotion', 'Department_Human Resources',
       'TrainingTimesLastYear', 'BusinessTravel_Non-Travel',
       'TotalWorkingYears', 'MaritalStatus_Divorced',
       'EnvironmentSatisfaction', 'target'],
      dtype='object')
Index(['WorkLifeBalance', 'Department_Sales', 'Gender', 'TotalWorkingYears',
       'YearsInCurrentRole', 'Age', 'Department_Human Resources',
       'RelationshipSatisfaction', 'TrainingTimesLastYear',
       'NumCompaniesWorked', 'StockOptionLevel',
       'BusinessTravel_Travel_Rarely', 'Department_Research & Development',
       'JobLevel', 'YearsAtCompany', 'EnvironmentSatisfaction', 'OverTime',
       'Education', 'target'],
      dtype='object')

In [27]:
from sklearn.tree import DecisionTreeClassifier
clf1 = DecisionTreeClassifier()
clf2 = DecisionTreeClassifier()
clf3 = DecisionTreeClassifier()

In [28]:

#clf1.fit(       xtrain. ,   ytrain)
clf1.fit(df1.iloc[:,:-1],df1.iloc[:,-1])
clf2.fit(df2.iloc[:,:-1],df2.iloc[:,-1])
clf3.fit(df3.iloc[:,:-1],df3.iloc[:,-1])

DecisionTreeClassifier()

In [29]:
clf1.predict([[0.00000000e+00, 5.00000000e+00, 4.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 3.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 2.43386243e-01, 0.00000000e+00,
       3.50000000e+01, 1.34900000e+03, 2.00000000e+00, 1.80000000e+01,
       0.00000000e+00, 7.00000000e+00]])

/Users/nithinys/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [30]:
clf2.predict([[0.00000000e+00, 5.00000000e+00, 4.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 3.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 2.43386243e-01, 0.00000000e+00,
       3.50000000e+01, 1.34900000e+03, 2.00000000e+00, 1.80000000e+01,
       0.00000000e+00, 7.00000000e+00]])

/Users/nithinys/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [31]:
clf3.predict([[0.00000000e+00, 5.00000000e+00, 4.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 3.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 2.43386243e-01, 0.00000000e+00,
       3.50000000e+01, 1.34900000e+03, 2.00000000e+00, 1.80000000e+01,
       0.00000000e+00, 7.00000000e+00]])

/Users/nithinys/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [32]:
len([0.00000000e+00, 5.00000000e+00, 4.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 3.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 2.43386243e-01, 0.00000000e+00,
       3.50000000e+01, 1.34900000e+03, 2.00000000e+00, 1.80000000e+01,
       0.00000000e+00, 7.00000000e+00]
    )

18

In [33]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(random_state=7, max_depth=4, n_estimators=200,max_samples=0.8)

In [34]:
rf_clf.fit(X_train, y_train)
y_pred = rf_clf.predict(X_test)
#print(classification_report(y_test, y_pred)

In [35]:
from sklearn.metrics import classification_report

In [36]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.87      0.89       309
           1       0.43      0.51      0.47        59

    accuracy                           0.82       368
   macro avg       0.67      0.69      0.68       368
weighted avg       0.83      0.82      0.82       368

In [37]:
print("Train accuracy: {:.2f}".format(rf_clf.score(X_train, y_train)*100))
print("Test accuracy: {:.2f}".format(rf_clf.score(X_test, y_test)*100))

Train accuracy: 88.26
Test accuracy: 81.52

In [38]:
from sklearn.model_selection import KFold, cross_validate

kfold = KFold(n_splits=10)
cv_acc_results = cross_validate(rf_clf, X_train, y_train, cv=kfold, scoring='accuracy', return_train_score=True)

In [39]:
print(f"K-Fold Accuracy Mean: \n Train: {cv_acc_results['train_score'].mean()*100:.2f} \n Validation: {cv_acc_results['test_score'].mean()*100:.2f}")

K-Fold Accuracy Mean:
 Train: 88.62
 Validation: 84.20

In [40]:
rf = RandomForestClassifier(oob_score=True)

In [41]:
rf.fit(X_train,y_train)

RandomForestClassifier(oob_score=True)

In [42]:
rf.oob_score_

0.9264069264069265

In [43]:
# GridSearchCV to find optimal n_estimators
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV


# specify number of folds for k-fold CV
n_folds = 5

# parameters to build the model on
parameters = {'max_depth': range(2, 20, 5),"n_estimators":[100,200,300]}

# instantiate the model
rf = RandomForestClassifier()


# fit tree on training data
rf = GridSearchCV(rf, parameters,
                    cv=n_folds,
                   scoring="accuracy",return_train_score=True)
rf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': range(2, 20, 5),
                         'n_estimators': [100, 200, 300]},
             return_train_score=True, scoring='accuracy')

In [44]:
from sklearn.model_selection import RandomizedSearchCV

In [45]:
# Create the parameter grid based on the results of random search
param_grid = {
    'max_depth': [4,8,10],
    'min_samples_leaf': range(100, 400, 200),
    'min_samples_split': range(200, 500, 200),
    'n_estimators': [100,200, 300],
    'max_features': [5, 10]
}
# Create a based model
rf = RandomForestClassifier()
# Instantiate the grid search model
random_search = RandomizedSearchCV(estimator = rf, param_distributions= param_grid,
                          cv = 3, n_jobs = -1,verbose = 1)

In [46]:
random_search.fit(X_train, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'max_depth': [4, 8, 10],
                                        'max_features': [5, 10],
                                        'min_samples_leaf': range(100, 400, 200),
                                        'min_samples_split': range(200, 500, 200),
                                        'n_estimators': [100, 200, 300]},
                   verbose=1)