In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

data = {
    "day": ["D1","D2","D3","D4","D5","D6","D7","D8","D9","D10","D11","D12","D13","D14"],
    "outlook": ["Sunny","Sunny","Overcast","Rain","Rain","Rain","Overcast",
                "Sunny","Sunny","Rain","Sunny","Overcast","Overcast","Rain"],
    "temp": ["Hot","Hot","Hot","Mild","Cool","Cool","Cool",
             "Mild","Cool","Mild","Mild","Mild","Hot","Mild"],
    "humidity": ["High","High","High","High","Normal","Normal","Normal",
                 "High","Normal","Normal","Normal","High","Normal","High"],
    "wind": ["Weak","Strong","Weak","Weak","Weak","Strong","Strong",
             "Weak","Weak","Weak","Strong","Strong","Weak","Strong"],
    "play": ["No","No","Yes","Yes","Yes","No","Yes",
             "No","Yes","Yes","Yes","Yes","Yes","No"]
}

df = pd.DataFrame(data)
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [ ]:
df.drop("day",axis=1,inplace=True)

In [ ]:
#sunny, hot,high, strong - yes

In [ ]:
p(yes |sunny, hot,high, strong ) = p(sunny, hot,high, strong |yes) * p(yes)
p(yes |sunny, hot,high, strong ) = p(sunny |yes) * p(hot |yes) * p(high |yes) * p(strong |yes) * p(yes)

p(no |sunny, hot,high, strong ) = p(sunny, hot,high, strong |no) * p(no)
p(no |sunny, hot,high, strong ) = p(sunny |no) * p(hot |no) * p(high |no) * p(strong |no) * p(no)

In [ ]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [ ]:
py = 9/14
pn = 5/14

In [ ]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [ ]:
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [ ]:
#p(overcast|NO) = P(o and NO)/ P(No)
pon = 0/5 #prob(overcast |no)
prn = 2/5
psn = 3/5

poy = 4/9
pry = 3/9
psy = 2/9

In [ ]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [ ]:
pcoolno = 1/5
photno = 2/5
pmildno = 2/5

pcoolyes = 3/9
photyes = 2/9
pmildyes = 4/9

In [ ]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [ ]:
phighno = 4/5
pnormalno = 1/5

phighyes = 3/9
pnormalyes = 6/9

In [ ]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [ ]:
pstrongno = 3/5
pweakno = 2/5

pstrongyes = 3/9
pweakyes = 6/9

In [ ]:
#sunny , hot, high, weak
print(psy *photyes *phighyes *pweakyes *py)

0.007054673721340387

In [ ]:
print(psn *photno *phighno *pweakno *pn)

0.02742857142857143